main: com.thegreatchicken.TGCPlugin.PluginLoader
name: TGCPlugin
description: Handle TGC-PVP Related systems
version: 26.1.2
api-version: 26.1.2
depend: [packetevents]
commands:
   usewarp:
      description: Use a warp
      usage: /usewarp <name>
   createwarp:
      description: Create a warp
      usage: /createwarp <name> <worldname> <x> <y> <z>
   removewarp:
      description: Remove a warp
      usage: /removewarp <name>
   statuswarp:
      description: Set the status of a warp
      usage: /statuswarp <name> <status { enabled, disabled }>
   listwarp:
      description: List existing warps
      usage: /listwarp
