main: com.thegreatchicken.TGCPlugin.PluginLoader
name: TGCPlugin
description: Handle TGC-PVP Related systems
version: 1.21.1
api-version: 1.13
depend: [ ProtocolLib, FastAsyncWorldEdit, CommandAPI ]
commands:
   usewarp:
      description: Use a warp
      usage: /usewarp <name>
   createwarp:
      description: Create a warp
      usage: /createwarp <name> <worldname> <x> <y> <z>
   removewarp:
      description: Remove a warp
      usage: /removewarp <name>
   statuswarp:
      description: Set the status of a warp
      usage: /statuswarp <name> <status { enabled, disabled }>
   listwarp:
      description: List existing warps
      usage: /listwarp
   webrush:
      description: Apply a World Edit Brush to a specific location
      usage: /webrush <x> <y> <z> <name> [...args]
